apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: langfuse
  namespace: production
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: langfuse.teamleaseregtech.com
      http:
        paths:
          # Worker health
          - path: /api/health
            pathType: Exact
            backend:
              service:
                name: langfuse-worker
                port:
                  number: 3030

          # Ingest + public API (this is critical)
          - path: /api/public
            pathType: Prefix
            backend:
              service:
                name: langfuse-web
                port:
                  number: 80

          # Default route
          - path: /
            pathType: Prefix
            backend:
              service:
                name: langfuse-web
                port:
                  number: 80
