apiVersion: v1
kind: Secret
metadata:
  name: langfuse-env
  namespace: production
type: Opaque
stringData:
  DATABASE_URL: postgresql://langfuse_user:Fg1%40qrp15@10.11.0.252:5432/langfuse_db

  NEXTAUTH_URL: https://langfuse.teamleaseregtech.com
  NEXTAUTH_SECRET: By8BwoYk9iaGXMZeh+J+Kh5jh6D9cbfSqNYtEYW/MfQ=
  SALT: oN6ZAY5lRU4iSgQ+f6aY7YotfuHKYbzX0uc4hmQTXeA=
  ENCRYPTION_KEY: b0ad882e8e83a9ab15da46385b30139bc0700f5b68bee1fc5cd5069994277693

  REDIS_HOST: 10.10.10.4
  REDIS_PORT: "6379"

  CLICKHOUSE_URL: http://clickhouse.production.svc.cluster.local:8123
  CLICKHOUSE_MIGRATION_URL: http://clickhouse.production.svc.cluster.local:9000

  CLICKHOUSE_USER: clickhouse
  CLICKHOUSE_PASSWORD: clickhouse

  TELEMETRY_ENABLED: "false"
  LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES: "true"
  AUTH_DISABLE_SIGNUP: "true"
