apiVersion: v1
kind: Secret
metadata:
  name: langfuse-env
  namespace: production
type: Opaque
stringData:
  # Database
  DATABASE_URL: postgresql://langfuse_user:Fg1%40qrp15@10.11.0.252:5432/langfuse_db

  # Auth
  NEXTAUTH_URL: https://langfuse.teamleaseregtech.com
  NEXTAUTH_SECRET: By8BwoYk9iaGXMZeh+J+Kh5jh6D9cbfSqNYtEYW/MfQ=
  SALT: oN6ZAY5lRU4iSgQ+f6aY7YotfuHKYbzX0uc4hmQTXeA=
  ENCRYPTION_KEY: b0ad882e8e83a9ab15da46385b30139bc0700f5b68bee1fc5cd5069994277693

  # Redis
  REDIS_HOST: 10.10.10.4
  REDIS_PORT: "6379"
  REDIS_PASSWORD: ""
  REDIS_URL: redis://10.10.10.4:6379

  # Clickhouse
  CLICKHOUSE_URL: clickhouse://clickhouse:clickhouse@clickhouse.production.svc.cluster.local:9000/langfuse
  CLICKHOUSE_MIGRATION_URL: clickhouse://clickhouse:clickhouse@clickhouse.production.svc.cluster.local:9000/langfuse
  CLICKHOUSE_USER: clickhouse
  CLICKHOUSE_PASSWORD: clickhouse

  # Disable telemetry
  TELEMETRY_ENABLED: "false"
  DISABLE_TELEMETRY: "true"
  LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES: "true"
  AUTH_DISABLE_SIGNUP: "true"

  # IMPORTANT â€“ Disable S3 Uploads to fix worker crash
  LANGFUSE_S3_EVENT_UPLOAD_ENABLED: "false"
  LANGFUSE_S3_EVENT_UPLOAD_BUCKET: "disabled"
  ZOD_ERROR_OVERRIDE: "true"
